# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5752932514ec0e6b77cccfa679393bc79c80fcb52ddecf482d65db5a3c7f24fabae95bcbcb76d5a9d73da73ad33ef9b38a54125a513acb64cc45036375256701

test:
  secret_key_base: f9bd48f73a3a7fde84c59903d3a3e195f1125f44ecf01c37ba767ad34cd1f3d5ad55f9dcd41ae8782e09f8b4008b65c34fafc05d792aa69ce15924de4bf7f6ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
