# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20ca41eae55475cbf49de0f8889286c555bb46f94c0cd2c213d56596192da6334ad3767d904a927a2a73bb2a5da544356c548b2570046ab55bcc4cf69ad5c5d9

test:
  secret_key_base: 3613bec5189824d3eb701e634d460a21637e005fb17ab35a9b08dd5fd4bef4ca547df338c8987d1dd879dfed57996b5a737bae5f36427048ef414218a05844d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
