# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 273d65725833fe06eb83fb8f250eff299d0473da2bc41ad7a8a00eb8c9aa68bf941d8280c2dcebb748f2b0e23703b51b65c4dbd7b2645df9d721c84a11dc73b0

test:
  secret_key_base: 9741275b6a6536067697f4f95ed71fdcf6021a962a34114b9a6653288f3da12690c8c03ba62ebfe851dc3267a78ec8274e31cd7fc0400d4e2e65def173829f61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
