# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35b838e0f5e3866614c0603a19d4627fee06fd36d045994740b04a06455414af74abde67c446e84ff1eed9ef0981a81d2c4cf4fdd4589d26ab229f53424e5ded

test:
  secret_key_base: 0f90ec05cb43dfc5bcdd99c8252f15883e2d380378a8dbea5e127af99c16da3313ac755908cd8b852effaddac06f4ffb41997e47843a1cd5182c0f60dc312ff0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
